### ISSUE TITLE
Move 'threadDelay' and 'time-units' utils into separate package

### ISSUE THREAD

**Issue by ChShersh** [serokell/serokell-util#22]
Often in projects you want something small from `serokell-util`. But you don't want to add `serokell-util` into dependencies because it's a huge bardaq and very big dependency. It would be nice to split `serokell-util` into smaller pieces. So let's begin this process.

I think 'time-units' utils and especially this function:

```haskell
-- | Convenient version of Control.Concurrent.threadDelay which takes
-- any time-unit and operates in any MonadIO
threadDelay :: (MonadIO m, TimeUnit unit) => unit -> m ()
threadDelay = liftIO . Concurrent.threadDelay . fromIntegral . toMicroseconds
```

should be moved into separate package. It can be our fork of 'time-units' or we can create new 'time-units' redesigning existing one (using new GHC 8 features). This 'threadDelay' function is very useful. And working with `Integer` as a time is very sad(((

P.S. This PR is motivated by reviewing code which works with `Integer` time. Such code is not pleasant to write, easy to mess up, very hard to review.

**Comment by ChShersh** [comment]
We have our own time units package now:

* [`o-clock`](https://github.com/serokell/o-clock)

But it's not usable for 2-3 months at least because it uses `ghc-8.4.1-alpha1`. So I propose to postpone removal of such functions from `serokell-util` until we release `o-clock`.

**Comment by ChShersh** [comment]
Now [`o-clock` is on Hackage](http://hackage.haskell.org/package/o-clock) and available for GHC-8.2.2. So it can be used instead of `time-units` package. And this migration can be performed.

**Comment by vrom911** [comment]
Do you mean to reexport time functions from `o-clock? Or just to remove it at all?

**Comment by ChShersh** [comment]
@vrom911 Just remove it ♻️
