### ISSUE TITLE
compile failures

### ISSUE THREAD

**Issue by hvr** [serokell/serokell-util#3]
Hi,

Your recent `serokell-util-0.1.2.2` release upload to Hackage fails to build, and consequently Hackage isn't able to generate HTML documentation for your package (and users downloading your package are likely to run into the same problem), c.f.

https://hackage.haskell.org/package/serokell-util-0.1.2.2/reports/

This is most likely the result of inaccurate version bounds (assuming the package built locally for you). 

The `cabal gen-bounds` command can be used to help infer an initial set of version bounds, see  [Cabal User Guide | Generating dependency version bounds](http://cabal.readthedocs.io/en/latest/developing-packages.html#generating-dependency-version-bounds) for more details. Or, if you prefer Stack, you can use the [`--pvp-bounds=both` flag](https://www.fpcomplete.com/blog/2015/09/stack-pvp) to ensure your uploaded package has more accurate version bounds.

If you have any questions, please let me know!

**Comment by gromakovsky** [comment]
Fixed in `serokell-util-0.1.2.3`.
