### ISSUE TITLE
Add safe Bool wrapper

### ISSUE THREAD

**Issue by ChShersh** [serokell/serokell-util#43]
Motivated by similar issue in `universum`:

* https://github.com/serokell/universum/issues/55

Often functions have several flags as arguments:

```haskel
foo :: Bool -> Bool -> Bool -> String -> String
foo isWord asCaseInsensitive hasPunctuation str = ...
```

While it's recommended to implement custom ADT for such cases, this is not always convenient. And we can't reuse `if-then-else` and _guard_ machinery for this. So it makes sense to me to implement some safe boolean wrapper, like this:

```haskell
newtype TBool (a :: k) = B Bool
```

So you can write something like this:

```
foo :: TBool 'Word -> TBool a -> TBool String -> String -> String
```

Any comments? @gromakovsky @neongreen @volhovm

**Comment by neongreen** [comment]
Me and @int-index came up with a solution that allows writing things like this:

```haskell
foo :: Flag "skip_verification"
    -> Flag "rollback_on_error"
    -> IO ()
foo (Flag skipVerification) (Flag rollbackOnError) = do
  print (skipVerification, rollbackOnError)

main = do
  foo (#skip_verification True)
      (#rollback_on_error False)
```

What do you think?

**Comment by ChShersh** [comment]
@neongreen This looks good to me! I like this approach.

**Comment by volhovm** [comment]
Bump, looks good. What extensions does it require?

**Comment by int-index** [comment]
The framework for named parameters is implemented:

https://github.com/int-index/named

There are a few administrative tasks remaining (supporting `stack`, older compiler versions, having CI, documentation) and then I will publish on Hackage.

It allows usage in the style that @neongreen demonstrated above, but also _unordered_ keyword arguments:

```
-- variation 1
foo ! #skip_verification True
    ! #rollback_on_error False

-- variation 2
foo ! #rollback_on_error False
    ! #skip_verification True
```

It has good type inference, does not use any unsafe features, and reports understandable errors when you forget a flag or supply an unneeded flag.

It is also generalized from `Bool` to any type of named parameters.

**Comment by ChShersh** [comment]
Closing this in favor of `named` library. Looks like it solves problem much better and we don't need our own dirty hacks.
