### ISSUE TITLE
Add utility feature to extract git revision

### ISSUE THREAD

**Issue by ChShersh** [serokell/serokell-util#61]
This can be helpful to display it with `--version` option. @int-index implemented this in `yt-utils`. You can see how it's done here:

* https://github.com/serokell/yt-utilities/pull/113/commits/b14dd70cba6319effe420373ac6bd4ad857459b5

**Comment by yorickvP** [comment]
Use https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_keyword_expansion
