### ISSUE TITLE
Add formatting-like trace

### ISSUE THREAD

**Issue by Martoon-00** [serokell/serokell-util#8]
This requires `formatting` library, so I drop my thoughts here, not in `universum`.

Hate to say it, but using `trace` like functions got painful, perhaps even for painful that ones from `Debug.Trace`.
I propose to add following functions:
* `traceF :: Format Text (a -> b -> ... -> Text) -> a -> b -> ... -> x -> x`
* `traceIdF :: Format Text (a -> b -> ... -> x -> Text) -> a -> b -> ... -> x -> x`

Compare:
* `traceF "nayn" x` vs `traceF @Text "nyan" x`
* `traceF ("nayn"%build) a x` vs `trace @Text ("nayn" <> show a) x` or `trace (sformat ("nyan"%build) a) x`
* `traceIdF build <long expression>` vs `(\x -> (trace $ show x) x) <long expression>`

I dunno how often everyone else uses debug printing, but in cases when I occur to need it, its usage turns into 120+ length rows and ugly brackets all over around, and that's unpleasant

**Comment by ChShersh** [comment]
Why use `formatting` and not [`fmt`](https://github.com/aelve/fmt)? Instead of

```haskell
traceF ("nayn"%build) a x
```

You can write

```haskell
trace ("nayn"#|a|#"") x
```

It's shorter and doesn't require implementation of custom formatters.

**Comment by Martoon-00** [comment]
Cool, this may play well.
What about `traceId`-like function?

**Comment by ChShersh** [comment]
Well, `traceId` has next signature:

```haskell
traceId :: String -> String
```

I never used it. `traceId str` is just `trace str str`. If you want to print some variable you probably want to add some tag to printed string. If you want to print only some label then current `traceId` is already ok for you. Though there's sense in adding `traceBuild :: Buildable b => b -> b`.

**Comment by Martoon-00** [comment]
Oh sure, I meant something `traceShowId`-like.
I don't want `traceBuild` exactly because I want to tag printed items

**Comment by ChShersh** [comment]
@Martoon-00 Sure, in that case you can add such functions if you find them convenient to use.
